### ISSUE TITLE
Not compatible with renovate bot

### ISSUE THREAD

**Issue by MaxWinterstein** [MaxWinterstein/shfmt-py#4]
As for now, this repo is not updateable by renovate bot. 

log:
```
               {
                 "datasource": "github-tags",
                 "depName": "maxwinterstein/shfmt-py",
                 "depType": "repository",
                 "lookupName": "maxwinterstein/shfmt-py",
                 "currentValue": "3.3.1.8",
                 "depIndex": 5,
                 "updates": [],
                 "warnings": [],
                 "versioning": "semver",
                 "skipReason": "invalid-value"
               },
```

As far as i understand all the wild discussions around there, the pre-commit manager uses `semver` to detect versions.

I like the reference towards the original version of shfmt but it results in an version that is not parsable as semver. (semver does not allow 3 dots).

There are multiple solutions to solve this on client side, but each user has to do it himself. 

I am not sure how to build a version string that fulfills my desire to have 
* the original shftm version 
* a continuous version number from this 'wrap'

e.g. `1.0.0-3.3.1` is not really good as a dash hints a pre-release version and even is this would result in a successful run of pre-commit its still ugly.

**Comment by root360-AndreasUlm** [comment]
Why not using the [build-metadata](https://semver.org/#spec-item-10) information and generate a version number like `3.4.3+1` while increasing the number after `+` for every fix of the packaging.
Maybe that is working fine for pre-commit and renovate bot. (Haven't tested this approach)

**Comment by MaxWinterstein** [comment]
Well, I think this brings some other problems, that +1 will not be updated to +2 in some cases.

> Build metadata MUST be ignored when determining version precedence. Thus two versions that differ only in the build metadata, have the same precedence.

**Comment by MaxWinterstein** [comment]
I deceided to decouple the versioning, and ensure that updates work for everyone.
